# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/thomaslynch/CLionProjects/DTraceConsumer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/thomaslynch/CLionProjects/DTraceConsumer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/thomaslynch/CLionProjects/DTraceConsumer/CMakeFiles /Users/thomaslynch/CLionProjects/DTraceConsumer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/thomaslynch/CLionProjects/DTraceConsumer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HelloWorldTest

# Build rule for target.
HelloWorldTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HelloWorldTest
.PHONY : HelloWorldTest

# fast build rule for target.
HelloWorldTest/fast:
	$(MAKE) -f CMakeFiles/HelloWorldTest.dir/build.make CMakeFiles/HelloWorldTest.dir/build
.PHONY : HelloWorldTest/fast

#=============================================================================
# Target rules for targets named BasicForkTest

# Build rule for target.
BasicForkTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicForkTest
.PHONY : BasicForkTest

# fast build rule for target.
BasicForkTest/fast:
	$(MAKE) -f CMakeFiles/BasicForkTest.dir/build.make CMakeFiles/BasicForkTest.dir/build
.PHONY : BasicForkTest/fast

#=============================================================================
# Target rules for targets named ReadFileTest

# Build rule for target.
ReadFileTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReadFileTest
.PHONY : ReadFileTest

# fast build rule for target.
ReadFileTest/fast:
	$(MAKE) -f CMakeFiles/ReadFileTest.dir/build.make CMakeFiles/ReadFileTest.dir/build
.PHONY : ReadFileTest/fast

#=============================================================================
# Target rules for targets named DTraceConsumer

# Build rule for target.
DTraceConsumer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DTraceConsumer
.PHONY : DTraceConsumer

# fast build rule for target.
DTraceConsumer/fast:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/build
.PHONY : DTraceConsumer/fast

IOHandler.o: IOHandler.cpp.o

.PHONY : IOHandler.o

# target to build an object file
IOHandler.cpp.o:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/IOHandler.cpp.o
.PHONY : IOHandler.cpp.o

IOHandler.i: IOHandler.cpp.i

.PHONY : IOHandler.i

# target to preprocess a source file
IOHandler.cpp.i:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/IOHandler.cpp.i
.PHONY : IOHandler.cpp.i

IOHandler.s: IOHandler.cpp.s

.PHONY : IOHandler.s

# target to generate assembly for a file
IOHandler.cpp.s:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/IOHandler.cpp.s
.PHONY : IOHandler.cpp.s

dtraceHandler.o: dtraceHandler.cpp.o

.PHONY : dtraceHandler.o

# target to build an object file
dtraceHandler.cpp.o:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/dtraceHandler.cpp.o
.PHONY : dtraceHandler.cpp.o

dtraceHandler.i: dtraceHandler.cpp.i

.PHONY : dtraceHandler.i

# target to preprocess a source file
dtraceHandler.cpp.i:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/dtraceHandler.cpp.i
.PHONY : dtraceHandler.cpp.i

dtraceHandler.s: dtraceHandler.cpp.s

.PHONY : dtraceHandler.s

# target to generate assembly for a file
dtraceHandler.cpp.s:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/dtraceHandler.cpp.s
.PHONY : dtraceHandler.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/DTraceConsumer.dir/build.make CMakeFiles/DTraceConsumer.dir/main.cpp.s
.PHONY : main.cpp.s

tests/BasicForkTest.o: tests/BasicForkTest.cpp.o

.PHONY : tests/BasicForkTest.o

# target to build an object file
tests/BasicForkTest.cpp.o:
	$(MAKE) -f CMakeFiles/BasicForkTest.dir/build.make CMakeFiles/BasicForkTest.dir/tests/BasicForkTest.cpp.o
.PHONY : tests/BasicForkTest.cpp.o

tests/BasicForkTest.i: tests/BasicForkTest.cpp.i

.PHONY : tests/BasicForkTest.i

# target to preprocess a source file
tests/BasicForkTest.cpp.i:
	$(MAKE) -f CMakeFiles/BasicForkTest.dir/build.make CMakeFiles/BasicForkTest.dir/tests/BasicForkTest.cpp.i
.PHONY : tests/BasicForkTest.cpp.i

tests/BasicForkTest.s: tests/BasicForkTest.cpp.s

.PHONY : tests/BasicForkTest.s

# target to generate assembly for a file
tests/BasicForkTest.cpp.s:
	$(MAKE) -f CMakeFiles/BasicForkTest.dir/build.make CMakeFiles/BasicForkTest.dir/tests/BasicForkTest.cpp.s
.PHONY : tests/BasicForkTest.cpp.s

tests/HelloWorldTest.o: tests/HelloWorldTest.cpp.o

.PHONY : tests/HelloWorldTest.o

# target to build an object file
tests/HelloWorldTest.cpp.o:
	$(MAKE) -f CMakeFiles/HelloWorldTest.dir/build.make CMakeFiles/HelloWorldTest.dir/tests/HelloWorldTest.cpp.o
.PHONY : tests/HelloWorldTest.cpp.o

tests/HelloWorldTest.i: tests/HelloWorldTest.cpp.i

.PHONY : tests/HelloWorldTest.i

# target to preprocess a source file
tests/HelloWorldTest.cpp.i:
	$(MAKE) -f CMakeFiles/HelloWorldTest.dir/build.make CMakeFiles/HelloWorldTest.dir/tests/HelloWorldTest.cpp.i
.PHONY : tests/HelloWorldTest.cpp.i

tests/HelloWorldTest.s: tests/HelloWorldTest.cpp.s

.PHONY : tests/HelloWorldTest.s

# target to generate assembly for a file
tests/HelloWorldTest.cpp.s:
	$(MAKE) -f CMakeFiles/HelloWorldTest.dir/build.make CMakeFiles/HelloWorldTest.dir/tests/HelloWorldTest.cpp.s
.PHONY : tests/HelloWorldTest.cpp.s

tests/ReadFileTest.o: tests/ReadFileTest.cpp.o

.PHONY : tests/ReadFileTest.o

# target to build an object file
tests/ReadFileTest.cpp.o:
	$(MAKE) -f CMakeFiles/ReadFileTest.dir/build.make CMakeFiles/ReadFileTest.dir/tests/ReadFileTest.cpp.o
.PHONY : tests/ReadFileTest.cpp.o

tests/ReadFileTest.i: tests/ReadFileTest.cpp.i

.PHONY : tests/ReadFileTest.i

# target to preprocess a source file
tests/ReadFileTest.cpp.i:
	$(MAKE) -f CMakeFiles/ReadFileTest.dir/build.make CMakeFiles/ReadFileTest.dir/tests/ReadFileTest.cpp.i
.PHONY : tests/ReadFileTest.cpp.i

tests/ReadFileTest.s: tests/ReadFileTest.cpp.s

.PHONY : tests/ReadFileTest.s

# target to generate assembly for a file
tests/ReadFileTest.cpp.s:
	$(MAKE) -f CMakeFiles/ReadFileTest.dir/build.make CMakeFiles/ReadFileTest.dir/tests/ReadFileTest.cpp.s
.PHONY : tests/ReadFileTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... HelloWorldTest"
	@echo "... BasicForkTest"
	@echo "... ReadFileTest"
	@echo "... DTraceConsumer"
	@echo "... IOHandler.o"
	@echo "... IOHandler.i"
	@echo "... IOHandler.s"
	@echo "... dtraceHandler.o"
	@echo "... dtraceHandler.i"
	@echo "... dtraceHandler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tests/BasicForkTest.o"
	@echo "... tests/BasicForkTest.i"
	@echo "... tests/BasicForkTest.s"
	@echo "... tests/HelloWorldTest.o"
	@echo "... tests/HelloWorldTest.i"
	@echo "... tests/HelloWorldTest.s"
	@echo "... tests/ReadFileTest.o"
	@echo "... tests/ReadFileTest.i"
	@echo "... tests/ReadFileTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

